### ISSUE TITLE
'SMSegmentAppearance' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by Geeo** [sima-11/SMSegmentView#24]
I try to init a SMSegmentAppearance :
let appearance = SMSegmentAppearance()

and get the following error : 'SMSegmentAppearance' initializer is inaccessible due to 'internal' protection level

**Comment by sima-11** [comment]
@Geeo - I think it should be fixed by just changing `internal` to `public`? As I've got very limited access to the internet at the moment, will have to push the changes this weekend.

**Comment by serhiisuprun** [comment]
Hi guys 
Any updates here ?

**Comment by sima-11** [comment]
@serhiisuprun Unfortunately I failed to do this last weekend. Will have to find another time. Sorry about that.

**Comment by Geeo** [comment]
Replacing internal by public work. This is a correct workaround in the meantime.

**Comment by simondec** [comment]
In the meantime, it is possible to alter the `SMSegmentView.segmentAppearance` property directly since [it is a variable initialized with a default `SMSegmentAppearance`](https://github.com/sima-11/SMSegmentView/blob/master/SMSegmentViewController/SMSegmentView/SMSegmentView.swift#L67):

```swift
segmentView.segmentAppearance?.segmentOffSelectionColour = UIColor.white
```

On a related side note, the `segmentAppearance` property shouldn't be declared as optional, and its initialization line should be moved up, [before the `super.init()` line](https://github.com/sima-11/SMSegmentView/blob/master/SMSegmentViewController/SMSegmentView/SMSegmentView.swift#L65).

**Comment by sima-11** [comment]
Has changed from `internal` to `public`. :]
